swagger: "2.0"
info:
  version: "0.0.1"
  title: DeadmanPi App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /status:
    # binds a127 app logic to a route
    x-swagger-router-controller: deadman_pi
    get:
      description: Returns status of server to the caller
      # used as the method name of the controller
      operationId: status
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/DeadmanPiResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /sensor:
    x-swagger-router-controller: deadman_pi
    get:
      description: Returns status of sensor to the caller
      operationId: sensor
      parameters:
        - name: name
          in: query
          description: The name of the sensor to access
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/DeadmanPiResponse"
        "400":
          description: Incorrect Sensor Name
          schema:
            $ref:  "#/definitions/ErrorResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
        
  /kill:
    x-swagger-router-controller: deadman_pi
    post:
      operationId: kill
      description: Kill the remote server
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/DeadmanPiResponse"
  /reset:
    x-swagger-router-controller: deadman_pi
    post:
      operationId: reset
      description: Reset the remote server
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/DeadmanPiResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  DeadmanPiResponse:
    required:
      - status
    properties:
      status: 
        type: string
      reason:
        type: string
      data:
        type: integer
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
